apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azurefile-secret
    shareName: {{ .Values.smb.shareName }}
    readOnly: false
  storageClassName: ""
